export type CatalogGroup = 'dairy' | 'meat' | 'grains' | 'snacks' | 'drinks' | 'pantry'
type Definition = readonly [name: string, aliases: string, tags: string, qualifier?: string]
export const catalogGroups: { id: CatalogGroup; name: string; entries: Definition[] }[] = [
  { id: 'dairy', name: 'Nabiał, jogurty i jajka', entries: [
    ['Serek wiejski', 'serek wiejski|cottage cheese', 'en:cottage-cheeses'],
    ['Serek wiejski lekki', 'serek wiejski light|light cottage cheese', 'en:cottage-cheeses', 'light|lekki|lekka|leicht'],
    ['Skyr naturalny', 'skyr naturalny|natural skyr|skyr nature', 'en:skyrs', 'natural|nature|plain|natur'],
    ['Skyr owocowy', 'skyr waniliowy|skyr truskawkowy|fruit skyr', 'en:skyrs', 'vanil|trusk|straw|fruit|owoc|mango|berry|blueberry|cherry'],
    ['Jogurt grecki', 'jogurt grecki|greek yogurt|greek yoghurt', 'en:greek-yogurts'],
    ['Jogurt naturalny', 'jogurt naturalny|natural yogurt|plain yogurt', 'en:plain-yogurts'],
    ['Jogurt pitny proteinowy', 'jogurt proteinowy|protein drink|protein drinking yoghurt', 'en:drinkable-yogurts|en:milk-protein-drinks', 'protein|bialk|high protein'],
    ['Mleko 1,5%', 'mleko 1.5|milk 1.5', 'en:milks|en:semi-skimmed-milks', '1[.,]5'],
    ['Mleko 2%', 'mleko 2%|milk 2%', 'en:milks|en:semi-skimmed-milks', '\\b2(?:[.,]0)?\\s?%'],
    ['Mleko 3,2%', 'mleko 3.2|milk 3.2', 'en:milks|en:whole-milks', '3[.,]2'],
    ['Twaróg półtłusty', 'twarog poltlusty|semi fat quark', 'en:quark', 'poltlust|semi'],
    ['Twaróg chudy', 'twarog chudy|low fat quark|magerquark', 'en:quark', 'chud|low fat|mager|lean'],
    ['Serek homogenizowany waniliowy', 'serek homogenizowany|danio|vanilla fromage frais', 'en:fromage-frais', 'wanil|vanil|danio'],
    ['Śmietana 18%', 'smietana 18|sour cream 18', 'en:sour-creams|en:creams', '18'],
    ['Śmietanka 30% lub 36%', 'smietanka|whipping cream|heavy cream', 'en:creams|en:whipping-creams', '30|36|whipp|heavy'],
    ['Masło extra 82%', 'maslo extra|butter 82', 'en:butters', '82|extra'],
    ['Margaryna', 'margaryna|margarine|kasia', 'en:margarines'],
    ['Ser gouda w plastrach', 'gouda', 'en:goudas'],
    ['Ser edamski w plastrach', 'edamski|edam', 'en:edam'],
    ['Mozzarella w kulce', 'mozzarella', 'en:mozzarella'],
    ['Ser feta lub typu greckiego', 'feta|ser typu greckiego|greek cheese', 'en:feta|en:greek-cheeses'],
    ['Halloumi', 'halloumi|hallumi', 'en:halloumi'],
    ['Camembert lub brie', 'camembert|brie', 'en:camemberts|en:brie'],
    ['Serek topiony', 'serek topiony|processed cheese|hochland', 'en:processed-cheese'],
    ['Jajka kurze M lub L', 'jajka|jaja kurze|eggs|eier', 'en:eggs|en:chicken-eggs'],
  ] },
  { id: 'meat', name: 'Mięso, wędliny i ryby', entries: [
    ['Pierś z kurczaka surowa', 'piers z kurczaka|chicken breast|filet z kurczaka', 'en:chicken-breasts'],
    ['Filet z indyka', 'filet z indyka|turkey breast|piers z indyka', 'en:turkey-breasts'],
    ['Mięso mielone z szynki', 'mielone z szynki|minced pork', 'en:minced-pork'],
    ['Mięso mielone drobiowe', 'mielone z indyka|mielone drobiowe|minced turkey|minced chicken', 'en:minced-turkey|en:minced-chicken'],
    ['Szynka z piersi kurczaka', 'szynka z kurczaka|chicken ham', 'en:chicken-hams'],
    ['Szynka z piersi indyka', 'szynka z indyka|turkey ham', 'en:turkey-hams'],
    ['Polędwica sopocka', 'poledwica sopocka|sopocka', ''],
    ['Kiełbasa krakowska sucha', 'krakowska|krakow sausage', 'en:krakowska-sausages'],
    ['Parówki z szynki lub drobiowe', 'parowki|berlinki|frankfurter', 'en:frankfurter-sausages'],
    ['Parówki z piersi kurczaka', 'parowki z kurczaka|parowki z piersi|chicken frankfurter', 'en:chicken-sausages'],
    ['Kabanosy drobiowe', 'kabanosy drobiowe|kabanos poultry|kabanosy z kurczaka', 'en:kabanos', 'drob|kurcz|chicken|poultry|indyk'],
    ['Kabanosy wieprzowe', 'kabanosy wieprzowe|pork kabanos', 'en:kabanos', 'wieprz|pork|schwein'],
    ['Boczek wędzony', 'boczek|bacon', 'en:bacons'],
    ['Szynka konserwowa', 'szynka konserwowa|canned ham', 'en:canned-hams'],
    ['Pasztet drobiowy', 'pasztet drobiowy|poultry pate|chicken pate', 'en:poultry-pates'],
    ['Tuńczyk w sosie własnym', 'tunczyk w sosie wlasnym|tuna in brine|tuna in water', 'en:tuna-in-brine|en:tuna-in-water'],
    ['Tuńczyk w oliwie', 'tunczyk w oliwie|tuna in olive oil', 'en:tuna-in-olive-oil'],
    ['Łosoś wędzony na zimno', 'losos wedzony|smoked salmon', 'en:smoked-salmon'],
    ['Łosoś wędzony na gorąco', 'losos wedzony na goraco|hot smoked salmon', 'en:smoked-salmon', 'goraco|hot smoked|heiss'],
    ['Surimi', 'surimi|paluszki krabowe|crab sticks', 'en:surimi'],
    ['Mintaj mrożony', 'mintaj|pollock|alaska pollack', 'en:pollock'],
    ['Miruna lub dorsz mrożony', 'miruna|filet z dorsza|filety z dorsza|hoki|cod fillet', 'en:cod-fillets|en:hoki'],
    ['Śledzie w oleju lub śmietanie', 'sledz|sledzie|herring|lisner', 'en:herrings'],
    ['Makrela wędzona', 'makrela|smoked mackerel', 'en:smoked-mackerel'],
    ['Pstrąg świeży lub wędzony', 'pstrag|trout|forelle', 'en:trouts'],
  ] },
  { id: 'grains', name: 'Pieczywo, zboża i produkty sypkie', entries: [
    ['Chleb żytni na zakwasie', 'chleb zytni|rye bread|sourdough rye', 'en:rye-breads'],
    ['Chleb tostowy', 'chleb tostowy|toast bread|sandwich bread', 'en:sliced-breads'],
    ['Bułki kajzerki', 'kajzerka|kajzerki|kaiser roll', 'en:kaiser-rolls'],
    ['Bułki grahamki', 'grahamka|grahamki|graham rolls|graham burger', 'en:wholemeal-rolls'],
    ['Chleb graham', 'chleb graham|graham bread', 'en:graham-breads'],
    ['Płatki owsiane', 'platki owsiane|oat flakes|oatmeal|haferflocken', 'en:oat-flakes'],
    ['Płatki jaglane lub gryczane', 'platki jaglane|platki gryczane|millet flakes|buckwheat flakes', 'en:millet-flakes|en:buckwheat-flakes'],
    ['Płatki kukurydziane', 'platki kukurydziane|corn flakes|cornflakes', 'en:corn-flakes'],
    ['Granola', 'granola', 'en:granolas'],
    ['Ryż biały', 'ryz bialy|white rice', 'en:white-rice'],
    ['Ryż basmati lub jaśminowy', 'basmati|jasminowy|jasmine rice', 'en:basmati-rices|en:jasmine-rices'],
    ['Ryż brązowy', 'ryz brazowy|brown rice|riz complet', 'en:brown-rices'],
    ['Kasza gryczana', 'kasza gryczana|buckwheat groats', 'en:buckwheat'],
    ['Kasza jaglana', 'kasza jaglana|millet groats', 'en:millet'],
    ['Kasza jęczmienna', 'kasza jeczmienna|barley groats|pearl barley', 'en:barley'],
    ['Kasza bulgur lub kuskus', 'bulgur|kuskus|couscous', 'en:bulgur|en:couscous'],
    ['Makaron pszenny świderki lub penne', 'swiderki|penne|fusilli', 'en:durum-wheat-pasta'],
    ['Makaron pełnoziarnisty', 'makaron pelnoziarnisty|whole wheat pasta|wholemeal pasta', 'en:whole-durum-wheat-pasta|en:wholemeal-pasta'],
    ['Makaron jajeczny nitki', 'makaron jajeczny|nitki|egg noodles', 'en:egg-pasta'],
    ['Mąka pszenna typ 450 lub 500', 'maka pszenna|wheat flour', 'en:wheat-flours', '450|500|tortow|all purpose'],
    ['Mąka żytnia', 'maka zytnia|rye flour', 'en:rye-flours'],
    ['Mąka pełnoziarnista', 'maka pelnoziarnista|maka graham|whole wheat flour', 'en:wholemeal-flours'],
    ['Bułka tarta', 'bulka tarta|breadcrumbs|bread crumbs', 'en:breadcrumbs'],
    ['Skrobia ziemniaczana', 'skrobia ziemniaczana|maka ziemniaczana|potato starch', 'en:potato-starches'],
    ['Płatki drożdżowe nieaktywne', 'platki drozdzowe|nutritional yeast|yeast flakes', 'en:nutritional-yeasts'],
  ] },
  { id: 'snacks', name: 'Przekąski, słodycze i batony proteinowe', entries: [
    ['Baton proteinowy Sante GO ON', 'go on protein|baton proteinowy sante', 'en:protein-bars|en:protein-energy-bars', 'sante|go on'],
    ['Baton proteinowy Allnutrition, SFD lub Kizzers', 'allnutrition protein|sfd protein|kizzers', 'en:protein-bars|en:protein-energy-bars', 'allnutrition|sfd|kizzers'],
    ['Baton proteinowy Barebells lub Nutrend', 'barebells protein bar|nutrend protein bar', 'en:protein-bars|en:protein-energy-bars', 'barebells|nutrend'],
    ['Czekolada mleczna', 'czekolada mleczna|milk chocolate|milchschokolade', 'en:milk-chocolates'],
    ['Czekolada gorzka 70% lub 80%', 'czekolada gorzka|dark chocolate', 'en:dark-chocolates'],
    ['Ciastka Oreo', 'oreo', 'en:oreo'],
    ['Delicje szampańskie', 'delicje|jaffa cakes', 'en:jaffa-cakes'],
    ['Ciastka Hit', 'hit ciastka|hit cocoa|hit wanilia', 'en:biscuits', '\\bhit\\b'],
    ['Kinder Bueno', 'kinder bueno', 'en:kinder-bueno'],
    ['Kinder Country', 'kinder country', ''],
    ['Snickers', 'snickers', ''],
    ['Mars, Twix lub Bounty', 'mars|twix|bounty', 'en:chocolate-bars', '\\bmars\\b|twix|bounty'],
    ['Chrupki kukurydziane', 'chrupki kukurydziane|corn puffs', 'en:corn-puffs'],
    ['Chipsy Lay’s', 'lays|lay s', 'en:potato-crisps|en:potato-chips', 'lay.?s'],
    ['Chipsy Doritos', 'doritos', 'en:tortilla-chips', 'doritos'],
    ['Paluszki słone', 'paluszki|salt sticks|lajkonik', 'en:salted-sticks'],
    ['Krakersy lub precelki', 'krakersy|krakers|crackers|precelki|pretzels', 'en:crackers|en:pretzels'],
    ['Orzechy nerkowca', 'nerkowce|nerkowca|cashews|cashew', 'en:cashew-nuts'],
    ['Orzechy włoskie', 'orzechy wloskie|walnuts', 'en:walnuts'],
    ['Migdały łuskane', 'migdaly|almonds|mandeln', 'en:almonds'],
    ['Orzeszki ziemne solone', 'orzeszki ziemne|salted peanuts', 'en:salted-peanuts'],
    ['Rodzynki lub żurawina suszona', 'rodzynki|raisins|zurawina|cranberries', 'en:raisins|en:dried-cranberries'],
    ['Daktyle suszone', 'daktyle|dried dates|dates', 'en:dates|en:dried-dates'],
    ['Galaretka owocowa w proszku', 'galaretka|jelly powder', 'en:jelly-powders'],
    ['Ryż preparowany lub wafle ryżowe', 'ryz preparowany|wafle ryzowe|rice cakes|puffed rice', 'en:rice-cakes|en:puffed-rice'],
  ] },
  { id: 'drinks', name: 'Napoje, soki i energetyki', entries: [
    ['Coca-Cola Zero', 'coca cola zero|coca-cola zero', 'en:colas', 'coca.?cola.*zero|zero.*coca'],
    ['Coca-Cola Original', 'coca cola original|coca-cola original', 'en:colas', 'coca.?cola.*original|original.*coca'],
    ['Pepsi Max', 'pepsi max', 'en:colas', 'pepsi.*max|max.*pepsi'],
    ['Fanta lub Sprite', 'fanta|sprite', 'en:sodas', 'fanta|sprite'],
    ['Monster Energy', 'monster', 'en:energy-drinks', 'monster'],
    ['Red Bull lub Red Bull Sugarfree', 'red bull', 'en:energy-drinks', 'red bull'],
    ['Tiger Energy Drink', 'tiger', 'en:energy-drinks', 'tiger'],
    ['Woda mineralna niegazowana', 'niegazowana|still mineral water|eau plate', 'en:non-carbonated-mineral-waters|en:still-waters'],
    ['Woda lekko gazowana', 'lekko gazowana|lightly sparkling|perlage', 'en:sparkling-mineral-waters'],
    ['Sok pomidorowy 100%', 'sok pomidorowy|tomato juice', 'en:tomato-juices'],
    ['Sok pomarańczowy 100%', 'sok pomaranczowy|orange juice', 'en:orange-juices'],
    ['Sok jabłkowy 100%', 'sok jablkowy|apple juice', 'en:apple-juices'],
    ['Napój owocowy Tymbark', 'tymbark', 'en:fruit-based-beverages', 'tymbark'],
    ['Lipton Ice Tea', 'lipton ice tea|lipton iced tea', 'en:iced-teas', 'lipton'],
    ['Kawa mrożona', 'kawa mrozona|caffe latte|iced coffee|kaffee', 'en:iced-coffees'],
    ['Piwo jasne', 'piwo jasne|lager|pilsner', 'en:lagers|en:pilsners'],
    ['Piwo bezalkoholowe 0%', 'piwo bezalkoholowe|alcohol free beer|non alcoholic beer', 'en:non-alcoholic-beers'],
    ['Napój izotoniczny Oshee lub 4Move', 'oshee|4move|izotoniczny|isotonic', 'en:isotonic-drinks|en:sports-drinks'],
    ['Woda smakowa', 'woda smakowa|flavoured water|flavored water', 'en:flavored-waters'],
    ['Sok z buraka lub marchwi', 'sok z buraka|sok marchwiowy|beetroot juice|carrot juice', 'en:carrot-juices|en:beetroot-juices'],
    ['Kombucha', 'kombucha', 'en:kombucha'],
    ['Napój owsiany lub migdałowy', 'napoj owsiany|napoj migdalowy|oat drink|almond drink', 'en:oat-milks|en:almond-milks'],
    ['Napój sojowy z wapniem', 'napoj sojowy|soya drink|soy drink', 'en:soy-milks'],
    ['Sok grejpfrutowy', 'sok grejpfrutowy|grapefruit juice', 'en:grapefruit-juices'],
    ['Woda kokosowa', 'woda kokosowa|coconut water', 'en:coconut-waters'],
  ] },
  { id: 'pantry', name: 'Dania gotowe, sosy i dodatki', entries: [
    ['Ketchup', 'ketchup', 'en:ketchup'],
    ['Majonez', 'majonez|mayonnaise', 'en:mayonnaises'],
    ['Musztarda', 'musztarda|mustard|senf', 'en:mustards'],
    ['Sos czosnkowy lub tysiąca wysp', 'sos czosnkowy|garlic sauce|thousand island|1000 wysp', 'en:garlic-sauces|en:thousand-island-dressings'],
    ['Sos sojowy', 'sos sojowy|soy sauce|soya sauce', 'en:soy-sauces'],
    ['Hummus', 'hummus|houmous', 'en:hummus'],
    ['Masło orzechowe 100%', 'maslo orzechowe|peanut butter', 'en:peanut-butters'],
    ['Dżem niskosłodzony lub 100% owoców', 'dzem|jam|fruit spread', 'en:jams|en:fruit-jams'],
    ['Nutella lub krem czekoladowy', 'nutella|krem czekoladowy|chocolate spread', 'en:chocolate-spreads|en:hazelnut-spreads'],
    ['Tortille pszenne', 'tortilla|tortille|wrap', 'en:wheat-tortillas'],
    ['Pizza Guseppe', 'guseppe|giuseppe', 'en:pizzas', 'guseppe|giuseppe'],
    ['Pizza Ristorante lub Feliciana', 'ristorante|feliciana', 'en:pizzas', 'ristorante|feliciana'],
    ['Pierogi z mięsem lub ruskie', 'pierogi|pierozki|dumplings', 'en:pierogi'],
    ['Warzywa na patelnię', 'warzywa na patelnie|stir fry vegetables|vegetable mix', 'en:frozen-mixed-vegetables'],
    ['Szpinak mrożony', 'szpinak|spinach|spinat', 'en:frozen-spinachs'],
    ['Frytki mrożone', 'frytki|french fries|pommes frites', 'en:frozen-french-fries'],
    ['Zupa instant Vifon', 'vifon|zupa instant|instant soup', 'en:instant-noodles|en:instant-soups'],
    ['Passata pomidorowa', 'passata|przecier pomidorowy', 'en:tomato-purees|en:passata'],
    ['Pomidory w puszce', 'pomidory krojone|tomatoes chopped|chopped tomatoes', 'en:canned-tomatoes'],
    ['Kukurydza konserwowa', 'kukurydza|sweet corn|sweetcorn', 'en:canned-sweetcorn'],
    ['Groszek konserwowy', 'groszek|green peas', 'en:canned-peas'],
    ['Ogórki konserwowe lub kiszone', 'ogorki|gherkins|pickled cucumbers', 'en:pickled-cucumbers'],
    ['Oliwa Extra Virgin', 'oliwa|olive oil', 'en:extra-virgin-olive-oils'],
    ['Olej rzepakowy', 'olej rzepakowy|rapeseed oil|canola oil', 'en:rapeseed-oils'],
    ['Ocet jabłkowy lub winny', 'ocet jablkowy|ocet winny|apple cider vinegar|apple vinegar|wine vinegar', 'en:apple-cider-vinegars|en:apple-vinegars|en:wine-vinegars'],
  ] },
]

export function catalogText(value: string): string {
  return value.toLocaleLowerCase('pl-PL').normalize('NFKD').replace(/\p{Diacritic}/gu, '').replace(/ł/g, 'l').replace(/[’']/g, ' ').replace(/\s+/g, ' ').trim()
}

export const requiredProducts = catalogGroups.flatMap((group, groupIndex) => group.entries.map((entry, index) => ({
  id: groupIndex * 25 + index + 1, group: group.id, name: entry[0],
  aliases: entry[1].split('|'), tags: entry[2] ? entry[2].split('|') : [],
  qualifier: entry[3] ?? null,
})))

export function matchingRequirements(name: string, brand: string, categories: string[]): number[] {
  const text = catalogText(`${name} ${brand}`)
  const padded = ` ${text} `
  const tags = new Set(categories)
  return requiredProducts.filter((entry) => {
    const base = entry.tags.some((tag) => tags.has(tag))
      || entry.aliases.some((alias) => padded.includes(` ${catalogText(alias)} `))
    return base && (!entry.qualifier || new RegExp(entry.qualifier).test(text))
  }).map((entry) => entry.id)
}
